"""
Synthetic 2D Binary Classification Dataset Generator (make_moons).

NOTE FOR TEAMMATES (Arjun, Achyut, Anirudh):
The CSVs (data/train.csv, data/val.csv, data/test.csv) and NPZ files
(data/train.npz, data/val.npz, data/test.npz) generated by this script
are ALREADY STANDARDIZED using the mean and standard deviation of the TRAIN split.
You DO NOT need to scale the data in your loader, inference scripts, or MATLAB code.
The mean and standard deviation are recorded in data/scaler.json purely for reference
or if raw out-of-distribution points need to be transformed in the future.
"""

from pathlib import Path
import json
import argparse
import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

def generate_and_save_data(
    n_samples: int = 6000,
    noise: float = 0.25,
    seed: int = 42,
    output_dir: str | Path = "data"
) -> dict:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Generate synthetic 2D data
    X, y = make_moons(n_samples=n_samples, noise=noise, random_state=seed)
    y = y.astype(np.int64)

    # 2. Stratified train (60%), val (20%), test (20%) split
    # First split off 60% train
    X_train, X_rem, y_train, y_rem = train_test_split(
        X, y,
        train_size=0.6,
        stratify=y,
        random_state=seed
    )
    # Split the remaining 40% into equal halves: 20% val, 20% test
    X_val, X_test, y_val, y_test = train_test_split(
        X_rem, y_rem,
        test_size=0.5,
        stratify=y_rem,
        random_state=seed
    )

    # 3. Standardize features using statistics from TRAIN split ONLY
    mean = X_train.mean(axis=0)
    std = X_train.std(axis=0)
    # Guard against zero std division if any feature is constant
    std = np.where(std == 0, 1.0, std)

    X_train_scaled = (X_train - mean) / std
    X_val_scaled = (X_val - mean) / std
    X_test_scaled = (X_test - mean) / std

    # Save scaler statistics
    scaler_info = {
        "mean": [float(m) for m in mean],
        "std": [float(s) for s in std],
        "is_already_scaled": True,
        "note": (
            "Features in train.csv, val.csv, test.csv and *.npz are ALREADY "
            "standardized using these train statistics. Do NOT re-scale them."
        ),
    }
    with open(output_dir / "scaler.json", "w", encoding="utf-8") as f:
        json.dump(scaler_info, f, indent=2)

    # Helper to save CSV and NPZ
    splits = {
        "train": (X_train_scaled, y_train),
        "val": (X_val_scaled, y_val),
        "test": (X_test_scaled, y_test),
    }

    for name, (X_split, y_split) in splits.items():
        # Save CSV: x1,x2,label
        csv_path = output_dir / f"{name}.csv"
        data_matrix = np.column_stack([X_split, y_split])
        np.savetxt(
            csv_path,
            data_matrix,
            delimiter=",",
            header="x1,x2,label",
            comments="",
            fmt=["%.8f", "%.8f", "%d"]
        )

        # Save NPZ: X, y
        npz_path = output_dir / f"{name}.npz"
        np.savez_compressed(npz_path, X=X_split.astype(np.float32), y=y_split.astype(np.int64))

    stats = {
        "total_samples": int(n_samples),
        "train_size": int(len(y_train)),
        "val_size": int(len(y_val)),
        "test_size": int(len(y_test)),
        "train_balance": {int(c): int((y_train == c).sum()) for c in np.unique(y_train)},
        "val_balance": {int(c): int((y_val == c).sum()) for c in np.unique(y_val)},
        "test_balance": {int(c): int((y_test == c).sum()) for c in np.unique(y_test)},
    }

    print("==================================================================")
    print("        SYNTHETIC DATASET GENERATION COMPLETE (make_moons)        ")
    print("==================================================================")
    print(f"Total samples : {stats['total_samples']} (noise={noise}, seed={seed})")
    print(f"Train split   : {stats['train_size']} samples | Class balance: {stats['train_balance']}")
    print(f"Val split     : {stats['val_size']} samples | Class balance: {stats['val_balance']}")
    print(f"Test split    : {stats['test_size']} samples | Class balance: {stats['test_balance']}")
    print("Feature scaling : Standardized on TRAIN statistics.")
    print("NOTE: All saved CSVs and NPZs are ALREADY scaled.")
    print(f"Saved artifacts to: {output_dir}")
    print("==================================================================")

    return stats

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate synthetic 2D binary classification dataset.")
    parser.add_argument("--samples", type=int, default=6000, help="Total number of samples (default 6000)")
    parser.add_argument("--noise", type=float, default=0.25, help="Gaussian noise std (default 0.25)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed (default 42)")
    parser.add_argument("--output-dir", type=str, default="data", help="Output directory (default 'data')")
    args = parser.parse_args()

    generate_and_save_data(
        n_samples=args.samples,
        noise=args.noise,
        seed=args.seed,
        output_dir=args.output_dir
    )

if __name__ == "__main__":
    main()
